### User Sign Up Endpoint
POST http://localhost:3001/v1/user
Content-Type: application/json

{
    "name": "Supriyanto",
    "company": "Tokopedia",
    "address": "Indonesia",
    "phone": "82301010940",
    "email": "supriyanto@mail.com",
    "password": "secret123"
}

### User Sign In Endpoint
POST http://localhost:3001/v1/user/login
Content-Type: application/json

{
    "email": "supriyanto@mail.com",
    "password": "secret123"
}